
package java8.SoapService.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://SoapService.java8/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns wsclient.Sinhvien
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SoapService.java8/SoapService/sayRequest", output = "http://SoapService.java8/SoapService/sayResponse")
    public Sinhvien say(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
